# Generated by Django 4.2.5 on 2023-09-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_carmark_alter_car_make_delete_carmake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='mark',
        ),
    ]
