# Generated by Django 4.2.5 on 2023-09-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_make_car_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mark',
            new_name='make',
        ),
    ]
